---
- hosts: spine
  user: root
  roles:
    - common
    - ibgp
  vars_files:
    - roles/ibgp/vars/main-2s2l.yml
  handlers:
    - include: handlers/main.yml

- hosts: leaf
  user: root
  roles:
    - common
    - ibgp
  vars_files:
    - roles/ibgp/vars/main-2s2l.yml
  handlers:
    - include : handlers/main.yml
